# Generated by Django 5.0.4 on 2024-04-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDrivers',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_avaliable', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'delivery_drivers',
                'managed': True,
            },
        ),
    ]
